# Generated by Django 5.2 on 2025-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_image", models.ImageField(upload_to="inputs/")),
                ("density_map", models.ImageField(upload_to="density_maps/")),
                ("model_name", models.CharField(max_length=4)),
                ("weight_selection", models.CharField(max_length=100)),
                ("event_city", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
