# Generated by Django 4.2.20 on 2025-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
