# Generated by Django 4.2.20 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={},
        ),
        migrations.RemoveField(
            model_name="observation",
            name="prediction",
        ),
        migrations.AddField(
            model_name="observation",
            name="density_map",
            field=models.ImageField(blank=True, null=True, upload_to="density_maps"),
        ),
        migrations.AddField(
            model_name="observation",
            name="input_image",
            field=models.ImageField(blank=True, null=True, upload_to="inputs"),
        ),
        migrations.AddField(
            model_name="observation",
            name="model_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="weight_selection",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
